app.I = find(app.volun.LastWord);
                if app.I == length(app.Diccionario)
                    app.I = 1;
                elseif isempty(app.I)
                    app.I = 1;
                else
                   app.I = app.I + 1;
                end
                app.Palabra.Text = app.volun.Diccionario(app.I);
                
                varname = {'ID' 'Edad' 'Sexo' 'Escolaridad'};
        volname = {'LastWord' 'Diccionario' 'Registro' 'Procesado'}
        mainfilename = 'main.csv'; % Registro de palabras por persona
        Diccionario = {'Gato'; 'Pera'; 'Mano'; 'Fresa'; 'Vaca'; 'Codo'; 'Sol';...
                       'Ventana'; 'El'; 'Niño'; 'Llora'; 'Hombre'; 'Camina';...
                       'Lentamente'; 'Por'; 'La'; 'Calle'; 'León'; 'Caballo';...
                       'Toro'; 'Perro'; 'Cabra'; 'Pájaro'; 'Pollo'; 'Cerdo';...
                       'Paloma'; 'Rata'; 'Cordero'; 'Gallo'; 'Ratón'; 'Mono';...
                       'Pez'; 'Gallina'; 'Serpiente'; 'Tigre'; 'Oso'; 'Canario';...
                       'Fue'; 'Forma'; 'Fueron'; 'Frente'; 'Fin'; 'Fuera';...
                       'Final'; 'Familia'; 'Falta'; 'Fuerza'; 'Fondo'; 'Futuro';...
                       'Figura', 'Fuerte', 'Fuente', 'Función', 'Favor',...
                       'Formación'; 'Fecha'; 'Fácil'};